CREATE SCHEMA IF NOT EXISTS traductordb ;
CREATE USER IF NOT EXISTS app@'%' IDENTIFIED BY '0000';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'app'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES